# GA parameters
POPULATION_SIZE = 15
MAX_NUMBER_OF_GENERATIONS = 25000
CROSSOVER_RATE = 0.75
MUTATION_RATE = 0.05
REPRODUCTION_RATE = 0.25
TERMINATION_CONDITION = 35  # Number of no improvements in the best fitness for a given number of generations

# item parameters
NUMBER_OF_ITEMS = 8
MAX_ITEM_WEIGHT = 12
MAX_ITEM_VALUE = 150
KNAPSACK_CAPACITY = 30
